FROM debian:bullseye

# install latest Octopus on Debian (develop branch)

# Convenience tools (up to emacs)
# Libraries that octopus needs 
# and optional dependencies (in alphabetical order)
RUN apt-get -y update && apt-get -y install wget time nano vim emacs \
    autoconf \
    automake \
    build-essential \
    fftw3-dev \
    g++ \
    gcc \
    gfortran \
    git \
    libatlas-base-dev \
    libblas-dev \
    libboost-dev \
    libcgal-dev \
    libelpa-dev \
    libetsf-io-dev \
    libfftw3-dev \
    libgmp-dev \
    libgsl-dev \
    liblapack-dev \
    liblapack-dev \
    libmpfr-dev \
    libnetcdff-dev \
    libnlopt-dev \
    libopenmpi-dev \
    libscalapack-mpi-dev \
    libspfft-dev \
    libtool \
    libxc-dev \
    libyaml-dev \
    openscad \
    openctm-tools \
    pkg-config \
    procps \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt
RUN git clone https://gitlab.com/octopus-code/octopus.git
WORKDIR /opt/octopus

# Record which version we are using
RUN git show > octopus-source-version
RUN echo "octopus-source-clone-date: $date " >> octopus-source-version

RUN autoreconf -i
RUN ./configure --enable-mpi --enable-openmp

# Which optional dependencies are missing?
RUN cat config.log | grep WARN > octopus-configlog-warnings
RUN cat octopus-configlog-warnings

# all in one line to make image smaller
RUN make && make install && make clean && make distclean

RUN octopus --version > octopus-version
RUN octopus --version

# The next command returns an error code as some tests fail
# RUN make check-short

RUN mkdir -p /opt/octopus-examples
COPY examples /opt/octopus-examples

# Instead of tests, run two short examples
RUN cd /opt/octopus-examples/recipe && octopus
RUN cd /opt/octopus-examples/h-atom && octopus
RUN cd /opt/octopus-examples/he && octopus

# allow root execution of mpirun
ENV OMPI_ALLOW_RUN_AS_ROOT=1
ENV OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1

# set number of OpenMP threads to 1 by default
ENV OMP_NUM_THREADS=1

# run one MPI-enable version
RUN cd /opt/octopus-examples/he && mpirun -np 1 octopus
RUN cd /opt/octopus-examples/he && mpirun -np 2 octopus

# offer directory for mounting container
RUN mkdir /io
WORKDIR /io

CMD bash -l
