FROM debian:bullseye

RUN mkdir -p  /opt/octopus/examples
COPY examples /opt/octopus/examples

RUN apt-get -y update
# Convenience tools
RUN apt-get -y install wget time nano vim emacs

# Libraries that octopus needs
RUN apt-get -y install git gcc g++ gfortran libxc-dev libblas-dev liblapack-dev libgsl-dev libfftw3-dev build-essential procps
# autoconf?

WORKDIR /opt
RUN wget -O oct.tar.gz http://octopus-code.org/down.php?file=11.1/octopus-11.1.tar.gz

RUN tar xfvz oct.tar.gz
RUN pwd
RUN ls -l 
WORKDIR /opt/octopus-11.1
# autoreconf -i
RUN ./configure
RUN make
RUN make install

RUN cd /opt/octopus/examples/h-atom && ./octopus

CMD bash -l

