FROM debian:bullseye

# install Octopus 12.1 on Debian

# Convenience tools (up to emacs)
# Libraries that octopus needs (up to procps)
# and optional dependencies (starting from libnetcdf-dev)
RUN apt-get -y update && apt-get -y install wget time nano vim emacs \
    autoconf libtool git gcc g++ gfortran libxc-dev libblas-dev liblapack-dev libgsl-dev libfftw3-dev build-essential procps \
    libnetcdff-dev libetsf-io-dev libspfft-dev libnlopt-dev libyaml-dev libgmp-dev libmpfr-dev libboost-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt
RUN wget -O oct.tar.gz http://octopus-code.org/down.php?file=12.1/octopus-12.1.tar.gz && tar xfvz oct.tar.gz && rm oct.tar.gz

WORKDIR /opt/octopus-12.1
RUN autoreconf -i
RUN ./configure

# Which optional dependencies are missing?
RUN cat config.log | grep WARN > octopus-configlog-warnings
RUN cat octopus-configlog-warnings

# all in one line to make image smaller
RUN make && make install && make clean && make distclean

RUN octopus --version > octopus-version
RUN octopus --version

# The next command returns an error code as some tests fail
# RUN make check-short

RUN mkdir -p /opt/octopus-examples
COPY examples /opt/octopus-examples

# Instead of tests, run two short examples
RUN cd /opt/octopus-examples/recipe && octopus
RUN cd /opt/octopus-examples/h-atom && octopus
RUN cd /opt/octopus-examples/he && octopus

# offer directory for mounting container
RUN mkdir /io
WORKDIR /io

CMD bash -l
