name: diff-with-upstream

on:
  schedule:
    - cron: "0 0 * * 0" # Run once a week on Sunday at midnight
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch and compare with upstream spack Octopus package file
      run: make diff
