name: osx-spack-v0.16.3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: install spack
        run: |
          git clone https://github.com/spack/spack.git s
          cd s && git checkout v0.16.3 && cd ..
          ./s/bin/spack --version
      - name: compile gcc10.3
        run: |
          pwd
          ls -l
          cp -v spack/package.py s/var/spack/repos/builtin/packages/octopus
          source s/share/spack/setup-env.sh && spack install gcc@10.3.0
          source s/share/spack/setup-env.sh && spack load gcc && spack compiler find
      - name: show spack compilers
        run: |
          spack compilers
          spack compiler info apple-clang
          spack compiler info gcc
      - name: compile octopus
        run: |
          # source s/share/spack/setup-env.sh && spack install octopus %gcc@10.3.0 ^cmake%apple-clang
          source s/share/spack/setup-env.sh && spack install octopus %gcc@10.3.0 
      - name: run smoke tests
        run: |
          echo "To be added"
