name: spack-develop

on:
  push:
    branches: [ spack-develop ]
  pull_request:
    branches: [ spack-develop ]
  schedule:
    # run once per week
    - cron: "9 0 * * 1"


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: make spack-develop
