name: spack-dev-build

on:
  workflow_dispatch:
  schedule:
     - cron:  '0 12 1 * *' # 12:00 UTC on the 1st of every month and on manual dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image with make checks
      run: make spack-dev-build
    
